### ISSUE TITLE
Switching to reader conditionals

### ISSUE THREAD

**Issue by danielcompton** [plumatic/schema#219]
Is there any interest in switching to 1.7's Reader Conditionals once they have been out for a while? There is the very real issue of supporting previous versions of Clojure which wouldn't work with Reader Conditionals. What's the plan for supporting older versions of Clojure?

**Comment by w01fe** [comment]
I think it would be prudent to wait until 1.7 has been out at least a year before starting this discussion, especially since AFAICT there's not much to gain from switching (besides simpler tooling for library maintainers) -- am I missing something there? 

 That said, if someone releases a tool that can produce a pre-1.7 compatible artifact from reader conditionals (essentially cljx updated for the new syntax) we could talk about switching sooner.

**Comment by danielcompton** [comment]
Simpler tooling was my main idea, although it is a pretty minor benefit when cljx is already setup.

**Comment by enaeher** [comment]
I'd like to make the case for switching to `cljc` sooner.

- cljx is deprecated by its author and no longer maintained. As a potential contributor I'd prefer not to spend time learning the idiosyncrasies of a tool which has already been deprecated.
- Jump-to-source IDE functionality like Cider's `cider-find-var` works correctly with reader conditionals but not with cljx. I'm also running into problems where sometimes the cljx nrepl middleware stops working and I can't compile files in Cider at all. (I'm sure this latter issue is fixable, but again, it feels like a waste of time to learn to fight a tool which has been superseded.)

**Comment by w01fe** [comment]
Those are fine points, but you haven't said anything about how to address pre-1.7 support.   Do you have anything to add there?

**Comment by danielcompton** [comment]
The only viable option I know of would be maintaining two release branches for a year and merging in patches from the 1.7 branch into 1.6. The cost benefit ratio doesn't seem worth it to me, but others may disagree.

**Comment by enaeher** [comment]
I don't know your requirements. If backward compatibility is a hard requirement, then you're right, there is no choice but to stay with cljx. (But given the prominent bold-faced warning in the README that this is alpha software and that APIs will change, I don't think breaking backward compatibility would catch anyone by surprise. People who didn't want to upgrade Clojure could continue using their current version of Schema. Only people who want to upgrade Schema but not Clojure would be affected.)

Even if it's premature to drop 1.6 support now, a year is a long time. The 2014 State of Clojure survey showed 90% of respondents using 1.6 roughly six months after its release (though some of those also had systems running 1.5).

My motivation for commenting here is that cljx problems are currently blocking me from working on a feature I'd hoped to propose. When I attempt to compile core.cljx in Cider with `cider-load-buffer`, despite the cljx documentation's claim:

> With cljx installed as a plugin, all nREPL evaluations and load-file operations will be processed by cljx appropriately before they reach the Clojure or ClojureScript compiler.

it appears to be sending the untransformed cljx file directly to Clojure:

```
2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling:
   /Users/eli/work/schema/src/cljx/schema/core.cljx:81:36

                 Compiler.java: 7137  clojure.lang.Compiler/load
                          REPL:    1  user/eval27227
                 Compiler.java: 6703  clojure.lang.Compiler/eval
                 Compiler.java: 6666  clojure.lang.Compiler/eval
                      core.clj: 2927  clojure.core/eval
                      main.clj:  239  clojure.main/repl/read-eval-print/fn
                      main.clj:  239  clojure.main/repl/read-eval-print
                      main.clj:  257  clojure.main/repl/fn
                      main.clj:  257  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   72  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  624  clojure.core/apply
                      core.clj: 1862  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  188  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  157  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run

1. Caused by java.lang.RuntimeException
   No reader function for tag +clj

               LispReader.java: 1180  clojure.lang.LispReader$CtorReader/readTagged
               LispReader.java: 1164  clojure.lang.LispReader$CtorReader/invoke
               LispReader.java:  609  clojure.lang.LispReader$DispatchReader/invoke
               LispReader.java: 1138  clojure.lang.LispReader/readDelimitedList
               LispReader.java:  972  clojure.lang.LispReader$ListReader/invoke
               LispReader.java: 1138  clojure.lang.LispReader/readDelimitedList
               LispReader.java:  972  clojure.lang.LispReader$ListReader/invoke
               LispReader.java:  183  clojure.lang.LispReader/read
```

I've seen this work in the past but it's not working now. I'd appreciate any thoughts you might have.

**Comment by w01fe** [comment]
Thanks for those details.  

I'm not sure what's up with the cljx plugin, it works fine for me.  Can you at least run the tests successfully?  It's not ideal, but you may be able to develop non-interactively, or develop just a Clojure version initially to spec things out.  What's the feature you're thinking about?

We're sensitive to making it easier to contribute, but for the time being I think more sensitive to compatibility (there are way more users of schema than contributors).  That may change in 6 months, however.

You're right about the alpha warning -- it's something we're very close to removing, however, and we have been committed to providing API compatibility nevertheless for some time now (the warning mostly refers to things changing under the hood for those developing tooling or custom schemas at the moment).  Moreover, it's not just a matter of people not upgrading schema if they don't upgrade Clojure, since other libraries depend on Schema.  Since we're likely at the bottom of the stack, breaking compatibility can also prevent people from bumping dependencies on *any* libraries they use.

**Comment by iku000888** [comment]
For what it is worth,
[cljsee(]https://github.com/aengelberg/cljsee) is available that is a solution to backwards compatibility by moving to reader conditionals.

**Comment by w01fe** [comment]
Thanks!  I'm not motivated to switch but if someone wants to tackle it we'd be happy to take a PR.

**Comment by iku000888** [comment]
Taking a stab at this...

**Comment by danielcompton** [comment]
T

**Comment by frenchy64** [comment]
Done!
