### ISSUE TITLE
StackOverflowError with s/protocol (when using io.aviso/pretty)

### ISSUE THREAD

**Issue by ikitommi** [plumatic/schema#277]
hi. 

bumped into this today:

```clj
lein try prismatic/schema

(require '[schema.core :as s])

(defprotocol Foo (foo [this]))

(s/validate (s/protocol Foo) 123)
; java.lang.StackOverflowError:
```

Am I doing something wrong here?

**Comment by w01fe** [comment]
Works fine for me, what Clojure version and schema version is this?

**Comment by ikitommi** [comment]
schema 1.0.1 
Clojure 1.7.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13
on osx

found already the cause - using [Ultra](https://github.com/venantius/ultra) for repl stuff, it uses [pretty](https://github.com/AvisoNovate/pretty) for better stacktraces. In this case, pretty's pretty-printer seems up filling the stack. Disabled the plugin and works as expected. 

Is there something that can be done for this in Schema side? Tried to read the code from schema, pretty and clojure.pprint, coudn't figure it out, schema exception referencing to itself? 

````
                             clojure.pprint/pprint-ideref       dispatch.clj:  130
                          clojure.pprint/pprint-ideref/fn       dispatch.clj:  133
                                 clojure.pprint/write-out    pprint_base.clj:  194
                                                      ...
                                clojure.pprint/pprint-map       dispatch.clj:   95
                             clojure.pprint/pprint-map/fn       dispatch.clj:   96
                          clojure.pprint/pprint-map/fn/fn       dispatch.clj:   96
                                 clojure.pprint/write-out    pprint_base.clj:  194
                                                      ...
                             clojure.pprint/pprint-ideref       dispatch.clj:  130
                          clojure.pprint/pprint-ideref/fn       dispatch.clj:  133
                                 clojure.pprint/write-out    pprint_base.clj:  194
                                                      ...
                                clojure.pprint/pprint-map       dispatch.clj:   95
                             clojure.pprint/pprint-map/fn       dispatch.clj:   96
                          clojure.pprint/pprint-map/fn/fn       dispatch.clj:   96
                                 clojure.pprint/write-out    pprint_base.clj:  194
                                                      ...
                             clojure.pprint/pprint-ideref       dispatch.clj:  130
                          clojure.pprint/pprint-ideref/fn       dispatch.clj:  133
                                 clojure.pprint/write-out    pprint_base.clj:  194
                                                      ...
```

**Comment by w01fe** [comment]
Protocols are cyclic internally.  

The default Clojure printer is fine with them, however.  Similarly, Schema installs a print-method that ensures proper printing of validation errors: https://github.com/Prismatic/schema/blob/master/src/cljx/schema/utils.cljx#L95.  

I'm not sure what ultra does, but my guess is it prevents one/both of these from working correctly.

**Comment by malchmih** [comment]
Have the same here. When I use `pretty` I get StackOverflow. And when I try to do this:
```clojure
      (catch Throwable t
        (clojure.repl/pst t))
```
I get:
```
Exception in thread "async-dispatch-21" java.lang.IllegalArgumentException: No implementation of method: :explain of protocol: #'schema.core/Schema found for class: clojure.lang.Var$Unbound
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:554)
	at schema.core$eval17497$fn__17498$G__17488__17503.invoke(core.clj:109)
	at schema.core.FnSchema.explain(core.clj:968)
	at schema.core$eval17525$fn__17526.invoke(core.clj:123)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at clojure.core$pr_on.invoke(core.clj:3548)
	at clojure.core$print_map$fn__5861.invoke(core_print.clj:212)
	at clojure.core$print_sequential.invoke(core_print.clj:59)
	at clojure.core$print_map.invoke(core_print.clj:209)
	at clojure.core$fn__5864.invoke(core_print.clj:219)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at clojure.core$pr_on.invoke(core.clj:3548)
	at clojure.core$print_map$fn__5861.invoke(core_print.clj:212)
	at clojure.core$print_sequential.invoke(core_print.clj:59)
	at clojure.core$print_map.invoke(core_print.clj:209)
	at clojure.core$fn__5864.invoke(core_print.clj:219)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at clojure.core$pr_on.invoke(core.clj:3548)
...
```

**Comment by ikitommi** [comment]
thanks guys. This is clearly not a schema problem.

**Comment by ikitommi** [comment]
btw, played with this a bit more, not going further as have no idea what those Schema-protocol implementations should actually do and what could break if I did that. Just not using Pretty for now.

```clojure
(require '[schema.core :as s])
=> nil
(defprotocol FOO (foo [this]))
=> FOO
(extend-protocol s/Schema
  Object
  (spec [this]
    (println "SPEC-object:" this)
    (s/spec String))
  (explain [_]
    (s/spec String)))

=> nil
(s/validate FOO 1)
SPEC-object: #object[user$eval7766$fn__7767 0x75d697e3 user$eval7766$fn__7767@75d697e3]
SPEC-object: #'user/foo
SPEC-object: :foo
SPEC-object: #'user/FOO
IllegalArgumentException No implementation of method: :spec of protocol: #'schema.core/Schema found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:554)
(extend-protocol s/Schema
  nil
  (spec [this]
    (println "SPEC-nil:" this)
    (s/spec String))
  (explain [_]
    (s/spec String)))

=> nil
(s/validate FOO 1)
SPEC-object: #object[user$eval7766$fn__7767 0x75d697e3 user$eval7766$fn__7767@75d697e3]
SPEC-object: #'user/foo
SPEC-object: :foo
SPEC-object: #'user/FOO
SPEC-nil: nil
SPEC-object: ([this])
SPEC-object: foo
SPEC-object: user.FOO
ExceptionInfo Value does not match schema: (not (map? 1))  schema.core/validator/fn--6722 (core.clj:151)
```

**Comment by malchmih** [comment]
Ok, I'll open another issue.

**Comment by hlship** [comment]
I'm not sure what's going on here ... I'd like to update Pretty to do the right thing, but from these comments, I don't have a handle on how the interaction between Pretty and Schema goes wrong.

**Comment by malchmih** [comment]
@hlship Will repository, reproducing the issue help?

**Comment by ikitommi** [comment]
reopened this as it seems we wan't to fix this.

**Comment by hlship** [comment]
Not sure if there's anything to be done on the io.aviso/pretty side.  If so, please fill me in and I'll do another release.

**Comment by w01fe** [comment]
Thanks @hlship.  Please pardon my lack of familiarity with `pretty`, but I would like to help address the issue on one side or another.  

As far as I understand it, the issue is that internally some schemas (and thus, ex-data in schema exceptions, which contain the root schemas) are cyclic, and printing these with `pretty` results in stack overflow.   With the default Clojure printer, there are a few layers that prevent this from happening:
 - The default REPL exception handler doesn't attempt to print the ex-data
 - `schema` installs a custom `print-method` for schemas, which calls `s/explain` to print a nice version (which is not cyclic).
 - Even if this `print-method` doesn't work, the default printer doesn't print the contents of vars (just the name).  This means you can print the contents of a protocol without things blowing up, although other cyclic data structures may still be problematic (the only case I can think of in schema is the experimental `abstract-map-schema`).

Given your knowledge of `pretty`, do you have ideas for how we can resolve this? 
 - Is there a way to make `pretty` use `print-method`, or a related plugin mechanism that `schema` could tap into?  
 - Or if in fact `pretty` blows up with cyclic data structures, is there a way to address that issue directly?  
 - Finally, I'm unsure if it's right to assume that `ex-data` should always be printable -- we've been treating it as a way to pass data to upstream callers that may want to do something programmatically with the exception, but maybe that's bad form?

Thanks!

**Comment by w01fe** [comment]
@hlship Do you have any feedback on the above questions?  If we can do anything to ease this on the Schema side I'd like to do it.  Thanks!

**Comment by hlship** [comment]
Thanks for the ping.

Pretty does have a way to deal with this kind of situation; it was introduced due to Component including the system map in its  exceptions, which could be comically verbose and repetitive.

The exception-dispatch multimethod is the hook that should allow for this. I could make Schema an optional dependency for Pretty, and add a namespace that would fix this.

Alternately, just adding an method to clojure.pprint/simple-dispatch would accomplish the same goal, from the schema side of things.

https://github.com/AvisoNovate/pretty/blob/master/src/io/aviso/exception.clj#L456

**Comment by w01fe** [comment]
Thanks @hlship !  

Adding a pprint method to schema definitely sounds like the simplest option -- I didn't realize that existed.   Does this look right to you? 

https://github.com/plumatic/schema/pull/344

I'd really appreciate your eyeballs, since plugging into pprint is new to me.  

Thanks again!
