### ISSUE TITLE
function type

### ISSUE THREAD

**Issue by sonwh98** [plumatic/schema#353]
Is there a function type? If not shouldn't there be? s/Func for example

**Comment by w01fe** [comment]
There is a function type, but it's purely descriptive (no validation of arguments or return, just that the object is a function).

  https://github.com/plumatic/schema/blob/master/src/cljx/schema/core.cljx#L1069

e.g. `(s/=> s/Int s/String s/String)` is a function that takes two strings and returns an int.

Also, can you please post questions on the mailing list (see the README) rather than as github issues in the future?  Thanks!
