### ISSUE TITLE
AOT Compilation Error on 1.7.0

### ISSUE THREAD

**Issue by adwelly** [plumatic/schema#355]
Requiring prismatic/schema "1.0.5"

I see the original issue has been closed while I was unavailable. I've now got a small project that consistently throws the exception:-

java.lang.ClassCastException: schema.utils.SimpleVCell cannot be cast to schema.utils.PSimpleCell

...during lein uberjar.

It's several fairly small files, but there's probably too much to paste in here. Is there anywhere helpful I can send this?

**Comment by w01fe** [comment]
Sorry for the issue thrash, and thanks for the offer! I think this is the same as #354, which was a new version of #351 -- can we keep the conversation in there, and I'll make sure that one stays as the canonical issue until it's fixed?  

As for the sample project -- that would be super-helpful, thanks!  Could you possibly put it on github as a project?  Or you can email me at publicgithub@w01fe.com if that's easier.  Ideally, if someone who knows AOT could figure out how to add this as a test for the main schema project, that would make it much easier to fix and ensure it stays fixed in the future.  

If you get a chance, I'd also definitely be interested to hear whether the workaround in #351, and/or the branch I linked in there, solves the issue.  

Thanks again!

**Comment by adwelly** [comment]
It's an otherwise meaningless little project that breaks when you do lein uberjar. Github is a bit of a showcase so I'd rather not leave it here - people might get the wrong impression :-)

I'll mail it to you and close this issue down; I will follow up on #354

**Comment by w01fe** [comment]
Sounds good, thanks!

**Comment by w01fe** [comment]
Oh, I guess looking at the error message this may be different -- you're seeing a ClassCast vs. a missing class.

**Comment by adwelly** [comment]
...oh?

I thought it was the class cast issue we were discussing? My bad I guess.
Well it sounds as if it's broken for you too which is helpful.

What issue number is this really?

**Comment by w01fe** [comment]
Yes, I can see the issue too.  I meant that #354 appears to be a different (but possibly related) issue involving the same classes.  I think I understand the problem here, and it would make sense that it happens if schema.utils is AOT compiled after your namespaces that define schematized functions.  It's an easy fix but would slow down the non-AOT case -- do you know if it's possible to detect AOT compilation at macroexpansion time?

**Comment by adwelly** [comment]
I've haven't heard of anything that detects AOT compilation at expansion
time - and it's a deep enough question that I think you'd probably be best
off enquiring at the one true source - Cognitect. Frankly - your work on
schemas is so important in the Clojure ecosystem that I would be astonished
if you didn't get a hearing and some advice.

I'm itching to ask you guys about the transition from Prismatic to
Plumatic; is there anything you can say in public?

Andy

**Comment by w01fe** [comment]
OK, I think I've figured out a solution that will solve this and #354 without hurting performance.  I'll try to put something up in the next day or two for you to try.  Basic idea is to get rid of the interface and deftype and just use an AtomicReference instead, which seems to have the same performance while sidestepping all the headaches of class generation and classloaders (and custom classes in lein-cljsbuild), etc.  

Re: plumatic, sorry but I can't say much of anything -- just that I and a couple of the other team members who left were allowed to take control of the existing repos under a new name.

**Comment by adwelly** [comment]
Well it's great news about 354 obviously, and I do understand about
Plumatic. Reading between the lines I suspect it is rather similar to what
happened to me just a few days back.

All the best.

Andy

**Comment by w01fe** [comment]
@adwelly I just tested and  `[prismatic/schema "1.1.1-SNAPSHOT"]` seems to work with the code you sent -- when you get a chance, can you please confirm?  Thanks!

**Comment by adwelly** [comment]
Well that was very quick work. Yes, it seems to work perfectly. I'll go
back to the original project which was much larger and give that a go.

Andy

**Comment by adwelly** [comment]
Yup. It's sorted out the much larger original project too. I thinks you've
nailed this one.

Andy

**Comment by w01fe** [comment]
Awesome, thanks for the follow-up!  I'll cut a 1.1.2 release now.
