### ISSUE TITLE
schema.core/validate: StackOverFlowError with either and recursive

### ISSUE THREAD

**Issue by elahti** [plumatic/schema#359]
Schema validation seems to fail to `StackOverFlowError` when using recursive schemas combined with `either`.

The following validation works:

```clojure
(s/defschema Recursive {:children [(s/recursive #'Recursive)]})
=> #'user/Recursive
(s/validate Recursive {:children []})
=> {:children []}
```

But the following doesn't:

```clojure
(s/defschema Recursive {:children [(s/either s/Str (s/recursive #'Recursive))]})
=> #'user/Recursive
(s/validate Recursive {:children []})
StackOverflowError   clojure.core/drop-while/fn--4862 (core.clj:2868)
```

I'm unsure if I'm just misusing the `either` there but it does work like that when it isn't used with `recursive`. For example `(s/either s/Str s/Int)` works just fine, allowing Integers or Strings.

I'm using schema.core version `1.1.1` with Clojure.

**Comment by w01fe** [comment]
Thanks for the report.  `either` is deprecated as of 1.0.0, and does not work with `recursive` anymore. Please replace `either` with `conditional`, `if`, or `cond-pre` (when applicable).   In this case, since `Str` and `Recursive` are superficially different, `cond-pre` will work as a drop-in replacement for `either`.

**Comment by elahti** [comment]
My bad. Thanks!
