### ISSUE TITLE
Coercion doesn't work for CondPre

### ISSUE THREAD

**Issue by laczoka** [plumatic/schema#373]
REPRODUCE:

``` clojure
(require '[clojure.edn :as edn])
(require '[schema.core :as s])
(require '[schema.coerce :as sc])

((sc/coercer (s/if sequential? [s/Int] s/Int) {s/Int edn/read-string}) "4") ;; works fine
((sc/coercer (s/cond-pre [s/Int] s/Int) {s/Int edn/read-string}) "4") ;; returns error
```

Is this by design?

**Comment by w01fe** [comment]
Not by design exactly, but I think it's as expected.  

Coercion happens once a schema has been selected for the data that knows how to coerce it, e.g., s/Int knows how to coerce from strings in the default coercer.  

But `(s/cond-pre [s/Int] s/Int)` expands to something like `(s/cond sequential? [s/Int] integer? s/Int)` so the conditional schema will fail to match on the string before the s/Int can be selected to coerce it.  

In principle I suppose coercion for Variants could attempt to coerce and then see if any of the alternatives match after coercing to them, but that goes against our general design principle of greedy matching without backtracking.  In this case, I would suggest either manually designing a schema such as your `if` that will work as desired, or (better, if possible IMHO) changing your data model to avoid the ambiguity in the first place.

**Comment by laczoka** [comment]
Hi Jason,

thanks, highlighting the design rationale is very helpful.

I am working working with some legacy code that used an earlier version schema (around 0.3.x) and I am trying to make the coercers work with the new constructs (cond-pre,conditional,contrained).

I'll direct my further questions to the mailing list.

**Comment by w01fe** [comment]
Sounds good.  

I should mention a third alternative: you can explicitly provide coercers for the composite schemas that are causing you trouble.  It's not as elegant but is the simplest approach that doesn't require changing the schemas themselves (or your data model).

**Comment by laczoka** [comment]
thanks, im happy to close this issue
