### ISSUE TITLE
Dump schema to json

### ISSUE THREAD

**Issue by achikin** [plumatic/schema#385]
Is there any way to dump schema to json to be used in documentation/help?

**Comment by w01fe** [comment]
I think one of the third-party libraries can probably do it (e.g. convert to swagger, and use that tooling -- see the README).  Built-in, you can just do `s/explain` and pretty-print to get a lisp-style readable representation.

Also, In the future, can you please ask questions on the mailing list rather than github issues?  Thanks!

**Comment by w01fe** [comment]
Err, I guess it's in the `fnhouse` readme: https://github.com/metosin/fnhouse-swagger.  If you're not using fnhouse, I assume you can probably still use the parts to do the same thing.

**Comment by achikin** [comment]
@w01fe we have already reused some parts of Swagger, but it produces something that is not quite easy to understand. Thank you for your suggestions!
