### ISSUE TITLE
schema.coerce - support String -> s/Bool [0.2.1]

### ISSUE THREAD

**Issue by hlship** [plumatic/schema#81]
Neither json-coercion-matcher nor string-coercion-matcher will coerce a string value to a boolean.

This is desirable for me, as sometimes I'm apply schema to query parameters and want to convert "true" and "false" to true and false.

**Comment by semperos** [comment]
@davegolland @w01fe Just my $0.02, thanks for all your excellent work on this library.

The `string->boolean` coercion is included with JSON's coercions by default. JSON, however, [already specifies](https://tools.ietf.org/html/rfc4627#section-2.1) `true` and `false` as legal values.

Given this, I think it's a mistake to include a default JSON coercion that transforms strings to booleans. It propagates sloppy JSON usage and becomes a source of hiding developer mistakes.

It would be easy enough for consumers of Schema's coercions to add this coercion explicitly if they need to support JSON payloads that don't use proper `true` and `false` values.

**Comment by w01fe** [comment]
Good point, I think this should probably have been added to string coercions, since it's not consistent with the rest of the defaults (e.g., number from string is also not part of JSON).  That said, someone could be using this productively now (e.g., for boolean keys in a map) so we'd have to treat it as a breaking change.  PR welcome!  Thanks for your $0.02 :)
